# Generated by Django 3.2.13 on 2022-07-30 11:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='başlık')),
                ('sm', models.TextField(max_length=200, verbose_name='özet')),
                ('content', ckeditor.fields.RichTextField(verbose_name='içerik')),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='fotoğraf ekle')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='ad')),
                ('yorum', models.CharField(max_length=500, verbose_name='yorum')),
                ('date', models.DateField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='data.data', verbose_name='article')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
