# Generated by Django 3.2.13 on 2022-07-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20220730_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='sm',
            field=models.TextField(max_length=800, verbose_name='özet'),
        ),
    ]
