# Generated by Django 3.2.13 on 2022-08-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_data_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='sm',
        ),
    ]
