# Generated by Django 3.2.13 on 2022-07-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='başlık')),
                ('sm', models.CharField(max_length=200, verbose_name='özet')),
                ('content', models.TextField(verbose_name='içerik')),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='fotoğraf ekle')),
            ],
        ),
    ]
