# Generated by Django 3.2.13 on 2022-07-26 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_article_sm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='sm',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='özet'),
            preserve_default=False,
        ),
    ]
