# Generated by Django 3.2.13 on 2022-07-26 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20220726_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='içerik'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='sm',
            field=models.TextField(max_length=200, verbose_name='özet'),
        ),
    ]
