# Generated by Django 3.2.13 on 2022-07-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20220726_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='fotoğraf ekle'),
        ),
    ]
