# Generated by Django 3.2.13 on 2022-07-29 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='ad',
        ),
        migrations.AddField(
            model_name='comment',
            name='yorum',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, verbose_name='başlık'),
            preserve_default=False,
        ),
    ]
