# Generated by Django 3.2.13 on 2022-07-29 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_alter_comment_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
    ]
