# Generated by Django 3.2.13 on 2022-08-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_alter_article_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='sm',
        ),
    ]
